// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyPbK5oR-lQOouRnBmwkEvprb8fuE8f6E',
    appId: '1:175561885327:web:a5c776cd5896c91bc292fa',
    messagingSenderId: '175561885327',
    projectId: 'mental-health-app-f4e0a',
    authDomain: 'mental-health-app-f4e0a.firebaseapp.com',
    storageBucket: 'mental-health-app-f4e0a.appspot.com',
    measurementId: 'G-PMQXGPQHJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc1ChbEH7Ny7JuWRY2HBTQFhHDpm5sVgE',
    appId: '1:175561885327:android:7e12a7fb4a554adbc292fa',
    messagingSenderId: '175561885327',
    projectId: 'mental-health-app-f4e0a',
    storageBucket: 'mental-health-app-f4e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUe0zq2iKA32PUV1sGXfBdn6J6n4_cqsg',
    appId: '1:175561885327:ios:2b2f5b95fdd97dfcc292fa',
    messagingSenderId: '175561885327',
    projectId: 'mental-health-app-f4e0a',
    storageBucket: 'mental-health-app-f4e0a.appspot.com',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUe0zq2iKA32PUV1sGXfBdn6J6n4_cqsg',
    appId: '1:175561885327:ios:2b2f5b95fdd97dfcc292fa',
    messagingSenderId: '175561885327',
    projectId: 'mental-health-app-f4e0a',
    storageBucket: 'mental-health-app-f4e0a.appspot.com',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyPbK5oR-lQOouRnBmwkEvprb8fuE8f6E',
    appId: '1:175561885327:web:b72c8c91a04360f0c292fa',
    messagingSenderId: '175561885327',
    projectId: 'mental-health-app-f4e0a',
    authDomain: 'mental-health-app-f4e0a.firebaseapp.com',
    storageBucket: 'mental-health-app-f4e0a.appspot.com',
    measurementId: 'G-JV6N9B4Q2S',
  );
}
