name: "Build & Release"

on:
  push:
    branches:
      - main
      - master
      - cicd

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter:latest

    defaults:
      run:
        working-directory: ./mobile

    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: dart pub upgrade --major-versions
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Run build runner
        run: flutter pub run build_runner build -d