name: "Build & Release"

on:
  push:
    branches:
      - main
      - master
      - cicd 

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./mobile

    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.0'
      - run: dart pub upgrade --major-versions

      - name: Setup Google-Services config file
        run: echo "${{ secrets.GOOGLE_SERVICES }}" > ./android/google-services.json
      
      - name: Setup firebase config file
        run: echo "${{ secrets.FIREBASE_JSON }}" > ./firebase.json

      - name: Setup keystore file
        run: echo $"{{ secrets.KEYSTORE }}" > ./android/upload-keystore.jks

      - name: Setup key.properties file
        run: |
          echo "storeFile=keystore.jks" > ./android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Get dependencies
        run: flutter pub get
      - name: Run build runner
        run: flutter pub run build_runner build -d

      - uses: KevinRohn/github-action-upload-play-store@v1.0.0
        with:
          service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          package_name: "com.mha.mental_health_app"
          aab_file_path: "./build/outputs/bundle/release/app-release.aab"
          track: "internal"
          release_status: "draft"

      - name: Remove Secret files from the machine
          run: |
            rm ./android/google-services.json
            rm ./firebase.json
            rm ./android/upload-keystore.jks
            rm ./android/key.properties
